.bash:
  variables:
    DOCKERFILE_DIR: dockerfiles/bash
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/bash.yml
        - dockerfiles/bash/*
        - .gitlab-ci.yml

test-bash:
  extends:
    - .test
    - .bash

build-bash:
  extends:
    - .build
    - .bash
  variables:
    CONTAINER_IMAGE_NAME: bash
  needs: [ "test-bash" ]
