.bedgraphtobigwig:
  variables:
    DOCKERFILE_DIR: dockerfiles/bedgraphtobigwig
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/bedgraphtobigwig.yml
        - dockerfiles/bedgraphtobigwig/*
        - .gitlab-ci.yml

test-bedgraphtobigwig:
  extends:
    - .test
    - .bedgraphtobigwig

build-bedgraphtobigwig:
  extends:
    - .build
    - .bedgraphtobigwig
  variables:
    CONTAINER_IMAGE_NAME: bedgraphtobigwig
  needs: [ "test-bedgraphtobigwig" ]
