.bedsort:
  variables:
    DOCKERFILE_DIR: dockerfiles/bedsort
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/bedsort.yml
        - dockerfiles/bedsort/*
        - .gitlab-ci.yml

test-bedsort:
  extends:
    - .test
    - .bedsort

build-bedsort:
  extends:
    - .build
    - .bedsort
  variables:
    CONTAINER_IMAGE_NAME: bedsort
  needs: [ "test-bedsort" ]
