.fastp:
  variables:
    DOCKERFILE_DIR: dockerfiles/fastp
  rules:
    - changes:
        - configs/gitlab-ci/fastp.yml
        - ${DOCKERFILE_DIR}/*
        - .gitlab-ci.yml

test-fastp:
  extends:
    - .test
    - .fastp

build-fastp:
  extends:
    - .build
    - .fastp
  variables:
    CONTAINER_IMAGE_NAME: fastp
  needs: [ "test-fastp" ]
