.fastp:
  variables:
    DOCKERFILE_DIR: dockerfiles/fastp
  rules:
    - changes:
        - configs/gitlab-ci/fastp.yml

test-fastp:
  extends:
    - .test
    - .fastp
  rules:
    - changes:
        - !reference [ .test, rules, changes ]
        - !reference [ .fastp, rules, changes ]

build-fastp:
  extends:
    - .build
    - .fastp
  variables:
    CONTAINER_IMAGE_NAME: fastp
  needs: [ "test-fastp" ]
  rules:
    - changes:
        - !reference [ .build, rules, changes ]
        - !reference [ .fastp, rules, changes ]
