.genrich:
  variables:
    DOCKERFILE_DIR: dockerfiles/genrich
  rules:
    - changes:
        - configs/gitlab-ci/genrich.yml

test-genrich:
  extends:
    - .test
    - .genrich
  rules:
    - changes:
        - !reference [ .test, rules, changes ]
        - !reference [ .genrich, rules, changes ]

build-genrich:
  extends:
    - .build
    - .genrich
  variables:
    CONTAINER_IMAGE_NAME: genrich
  needs: [ "test-genrich" ]
  rules:
    - changes:
        - !reference [ .build, rules, changes ]
        - !reference [ .genrich, rules, changes ]
