.genrich:
  variables:
    DOCKERFILE_DIR: dockerfiles/genrich
  # TODO: It would be nice to use DOCKERFILE_DIR in rules:changes. It doesn't work when tested for in 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/genrich.yml
        - dockerfiles/genrich/*
        - .gitlab-ci.yml

test-genrich:
  extends:
    - .test
    - .genrich

build-genrich:
  extends:
    - .build
    - .genrich
  variables:
    CONTAINER_IMAGE_NAME: genrich
  needs: [ "test-genrich" ]
