.genrich:
  variables:
    DOCKERFILE_DIR: dockerfiles/genrich
  rules:
    - changes:
        - configs/gitlab-ci/genrich.yml

test-genrich:
  extends:
    - .test
    - .genrich

build-genrich:
  extends:
    - .build
    - .genrich
  variables:
    CONTAINER_IMAGE_NAME: genrich
  needs: [ "test-genrich" ]
