.moods:
  variables:
    DOCKERFILE_DIR: dockerfiles/moods
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/moods.yml
        - dockerfiles/moods/*
        - .gitlab-ci.yml

test-moods:
  extends:
    - .test
    - .moods

build-moods:
  extends:
    - .build
    - .moods
  variables:
    CONTAINER_IMAGE_NAME: moods
  needs: [ "test-moods" ]
