.multiqc:
  variables:
    DOCKERFILE_DIR: dockerfiles/multiqc
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/multiqc.yml
        - dockerfiles/multiqc/*
        - .gitlab-ci.yml

test-multiqc:
  extends:
    - .test
    - .multiqc

build-multiqc:
  extends:
    - .build
    - .multiqc
  variables:
    CONTAINER_IMAGE_NAME: multiqc
  needs: [ "test-multiqc" ]
