.samtools:
  variables:
    DOCKERFILE_DIR: dockerfiles/samtools
  # TODO: It would be nice to use DOCKERFILE_DIR in rules:changes. It doesn't work when tested for in 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/samtools.yml
        - dockerfiles/samtools/*
        - .gitlab-ci.yml

test-samtools:
  extends:
    - .test
    - .samtools

build-samtools:
  extends:
    - .build
    - .samtools
  variables:
    CONTAINER_IMAGE_NAME: samtools
  needs: [ "test-samtools" ]
