.wiggletools:
  variables:
    DOCKERFILE_DIR: dockerfiles/wiggletools
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/wiggletools.yml
        - dockerfiles/wiggletools/*
        - .gitlab-ci.yml

test-wiggletools:
  extends:
    - .test
    - .wiggletools

build-wiggletools:
  extends:
    - .build
    - .wiggletools
  variables:
    CONTAINER_IMAGE_NAME: wiggletools
  needs: [ "test-wiggletools" ]
