services:
  - docker:20-dind

stages:
  - test
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  RDR_DOCKER_CONFIG_DIR: .

.test:
  image: docker:20.10
  stage: test
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - |
      if [ -f ${DOCKERFILE_DIR}/docker-compose.test.yml ]; then
          docker compose \
          --file ${DOCKERFILE_DIR}/docker-compose.test.yml up \
          --build \
          --exit-code-from sut
      else
          docker build \
          ${DOCKERFILE_DIR} \
          --file ${DOCKERFILE_DIR}/Dockerfile
      fi
  rules:
    - changes:
        - ${DOCKERFILE_DIR}/*
        - .gitlab-ci.yml

.build:
  image: docker:20.10
  stage: build
  variables:
    CR_NAME: ${CI_REGISTRY_IMAGE}/${CONTAINER_IMAGE_NAME}:latest
    DOCKERHUB_NAME: ensemblorg/${CONTAINER_IMAGE_NAME}:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull --rm=true -t ${CR_NAME} ${DOCKERFILE_DIR}
    - docker push ${CR_NAME}
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker tag ${CR_NAME} ${DOCKERHUB_NAME}
    - docker push ${DOCKERHUB_NAME}
  after_script:
    - docker logout ${CI_REGISTRY}
  rules:
    - changes:
        - ${DOCKERFILE_DIR}/*
        - .gitlab-ci.yml

test-fastp:
  extends: .test
  variables:
    DOCKERFILE_DIR: ./dockerfiles/fastp


build-fastp:
  extends: .build
  variables:
    DOCKERFILE_DIR: ./dockerfiles/fastp
    CONTAINER_IMAGE_NAME: fastp
  needs: [ "test-fastp" ]
