services:
  - docker:20-dind

include:
  - local: 'configs/gitlab-ci/**.yml'

stages:
  - test
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

.test:
  image: docker:20.10
  stage: test
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - |
      if [ -f ${DOCKERFILE_DIR}/docker-compose.test.yml ]; then
          docker compose \
          --file ${DOCKERFILE_DIR}/docker-compose.test.yml up \
          --build \
          --exit-code-from sut
      else
          docker build \
          ${DOCKERFILE_DIR} \
          --file ${DOCKERFILE_DIR}/Dockerfile
      fi
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.build:
  image: docker:20.10
  stage: build
  variables:
    CR_NAME: ${CI_REGISTRY_IMAGE}/${CONTAINER_IMAGE_NAME}
    #    DOCKERHUB_NAME: ensemblorg/${CONTAINER_IMAGE_NAME
    # TODO: Consider splitting this into two jobs, one for building and one for pushing
    # TODO: Consider splitting in different jobs pushing to GitLab Container Registry and Docker Hub
  before_script:
    - docker info
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker pull ${CR_NAME}:latest || true
    - docker build --cache-from ${CR_NAME}:latest --rm=true -t ${CR_NAME}:${CI_COMMIT_SHA} ${DOCKERFILE_DIR}
    - SOFTWARE_VERSION=$(docker inspect --format '{{ index .Config.Labels "software.version"}}' ${CR_NAME}:${CI_COMMIT_SHA})
    - docker tag ${CR_NAME}:${CI_COMMIT_SHA} ${CR_NAME}:${SOFTWARE_VERSION}
    - docker push ${CR_NAME}:${SOFTWARE_VERSION}
    - docker tag ${CR_NAME}:${CI_COMMIT_SHA} ${CR_NAME}:${SOFTWARE_VERSION}-${CI_COMMIT_SHORT_SHA}
    - docker push ${CR_NAME}:${SOFTWARE_VERSION}-${CI_COMMIT_SHORT_SHA}
    - LATEST_VERSION=$(docker inspect --format '{{ index .Config.Labels "software.latest_version"}}' ${CR_NAME})
    - if [ "${LATEST_VERSION}" == "true" ]; then docker tag ${CR_NAME}:${CI_COMMIT_SHA} ${CR_NAME}:latest; docker push ${CR_NAME}:latest; fi
    # TODO: More secure way to authenticate to Docker Hub
    # - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    # - docker tag ${CR_NAME}:latest ${DOCKERHUB_NAME}:latest
    # - docker tag ${CR_NAME}:latest ${DOCKERHUB_NAME}:${SOFTWARE_VERSION}
    # - docker push ${DOCKERHUB_NAME}:latest
    # - docker push ${DOCKERHUB_NAME}:${SOFTWARE_VERSION}
  after_script:
    - docker logout ${CI_REGISTRY}
  retry:
    max: 2
    when:
      - runner_system_failure


