.sn-barcode-correction-0.2.0:
  variables:
    IMAGE_NAME: sn-barcode-correction
    IMAGE_VERSION: 0.2.0
    DOCKERFILE_DIR: dockerfiles/${IMAGE_NAME}/${IMAGE_VERSION}
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/sn-barcode-correction/0.2.0.yml
        - dockerfiles/sn-barcode-correction/0.2.0/*
        - .gitlab-ci.yml

test-sn-barcode-correction-0.2.0:
  extends:
    - .test
    - .sn-barcode-correction-0.2.0
  needs: [ "build-sn-barcode-correction-0.2.0" ]

build-sn-barcode-correction-0.2.0:
  extends:
    - .build
    - .sn-barcode-correction-0.2.0
  variables:
    CONTAINER_IMAGE_NAME: ${IMAGE_NAME}
  


scan-sn-barcode-correction-0.2.0:
  extends:
    - .container_scanning
    - .sn-barcode-correction-0.2.0
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_VERSION}
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "test-sn-barcode-correction-0.2.0" ]

scan-sn-barcode-correction-latest:
  extends:
    - .container_scanning
    - .sn-barcode-correction-0.2.0
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "test-sn-barcode-correction-0.2.0" ]
