.multiqc-1.22:
  variables:
    IMAGE_NAME: multiqc
    IMAGE_VERSION: "1.22"
    DOCKERFILE_DIR: dockerfiles/${IMAGE_NAME}/${IMAGE_VERSION}
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/multiqc/1.22.yml
        - dockerfiles/multiqc/1.22/*
        - .gitlab-ci.yml

test-multiqc-1.22:
  extends:
    - .test
    - .multiqc-1.22
  needs: [ "build-multiqc-1.22" ]

build-multiqc-1.22:
  extends:
    - .build
    - .multiqc-1.22
  variables:
    CONTAINER_IMAGE_NAME: ${IMAGE_NAME}
  

scan-multiqc-1.22:
  extends:
    - .container_scanning
    - .multiqc-1.22
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_VERSION}
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "test-multiqc-1.22" ]

scan-multiqc-latest:
  extends:
    - .container_scanning
    - .multiqc-1.22
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "test-multiqc-1.22" ]