.bedsort-v369:
  variables:
    IMAGE_NAME: bedsort
    IMAGE_VERSION: v369
    DOCKERFILE_DIR: dockerfiles/${IMAGE_NAME}/${IMAGE_VERSION}
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/bedsort/v369.yml
        - dockerfiles/bedsort/v369/*
        - .gitlab-ci.yml

test-bedsort-v369:
  extends:
    - .test
    - .bedsort-v369

build-bedsort-v369:
  extends:
    - .build
    - .bedsort-v369
  variables:
    CONTAINER_IMAGE_NAME: ${IMAGE_NAME}
  needs: [ "test-bedsort-v369" ]


scan-bedsort-v369:
  extends:
    - .container_scanning
    - .bedsort-v369
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_VERSION}
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "build-bedsort-v369" ]

scan-bedsort-latest:
  extends:
    - .container_scanning
    - .bedsort-v369
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "build-bedsort-v369" ]