.wiggletools-1.2.11:
  variables:
    IMAGE_NAME: wiggletools
    IMAGE_VERSION: 1.2.11
    DOCKERFILE_DIR: dockerfiles/${IMAGE_NAME}/${IMAGE_VERSION}
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/wiggletools/1.2.11.yml
        - dockerfiles/wiggletools/1.2.11/*
        - .gitlab-ci.yml

test-wiggletools-1.2.11:
  extends:
    - .test
    - .wiggletools-1.2.11

build-wiggletools-1.2.11:
  extends:
    - .build
    - .wiggletools-1.2.11
  variables:
    CONTAINER_IMAGE_NAME: ${IMAGE_NAME}
  needs: [ "test-wiggletools-1.2.11" ]


scan-wiggletools-1.2.11:
  extends:
    - .container_scanning
    - .wiggletools-1.2.11
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_VERSION}
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "build-wiggletools-1.2.11" ]

scan-wiggletools-latest:
  extends:
    - .container_scanning
    - .wiggletools-1.2.11
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "build-wiggletools-1.2.11" ]