.sra-toolkit-3.3.0:
  variables:
    IMAGE_NAME: sra-toolkit
    IMAGE_VERSION: 3.3.0
    DOCKERFILE_DIR: dockerfiles/${IMAGE_NAME}/${IMAGE_VERSION}
  # TODO: It would be good if we could use DOCKERFILE_DIR in rules:changes. It didn't work when I tested it in GitLab 15.11.6-ee
  rules:
    - changes:
        - configs/gitlab-ci/sra-toolkit/3.3.0.yml
        - dockerfiles/sra-toolkit/3.3.0/*
        - .gitlab-ci.yml

test-sra-toolkit-3.3.0:
  extends:
    - .test
    - .sra-toolkit-3.3.0
  needs: [ "build-sra-toolkit-3.3.0" ]

build-sra-toolkit-3.3.0:
  extends:
    - .build
    - .sra-toolkit-3.3.0
  variables:
    CONTAINER_IMAGE_NAME: ${IMAGE_NAME}
  


scan-sra-toolkit-3.3.0:
  extends:
    - .container_scanning
    - .sra-toolkit-3.3.0
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_VERSION}
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "test-sra-toolkit-3.3.0" ]

scan-sra-toolkit-latest:
  extends:
    - .container_scanning
    - .sra-toolkit-3.3.0
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest
    CS_DOCKERFILE_PATH: ${DOCKERFILE_DIR}/Dockerfile
  needs: [ "test-sra-toolkit-3.3.0" ]
